# syntax=docker/dockerfile:1
FROM node:22-alpine

WORKDIR /usr/src/app

# Clone official Zotero stream-server
RUN apk add --update --no-cache git && \
    git clone --depth=1 https://github.com/zotero/stream-server.git .

RUN npm install

COPY stream-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/stream-entrypoint.sh

EXPOSE 8080

CMD ["/usr/local/bin/stream-entrypoint.sh"]